apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-minikube-three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-minikube-three
  template:
    metadata:
      labels:
        app: library-minikube-three
    spec:
      containers:
      - name: library-minikube-three
        image: libraryservice:local
        ports:
        - containerPort: 80
        - containerPort: 44363
---
apiVersion: v1
kind: Service
metadata:
  name: library-minikube-three
spec:
  selector:
    app: library-minikube-three
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 44363
      targetPort: 44363
  type: NodePort
